### ISSUE TITLE
Problem Regarding noun

### ISSUE THREAD

**Issue by amitojsingh** [yohasebe/engtagger#11]
I was using proper noun
If I place "India" with I capital engtagger recognize as a proper noun but What if I mistakenly put "india" with i down case it won't recognize as Proper noun. And if I make c capital in City, it recognise are proper noun but city is not a proper noun. Is Proper Noun algorithm is only based on capital letters?

**Comment by yohasebe** [comment]
That is what is expected. EngTagger is not good at distinguishing proper nouns from common nouns since it it is statistically-based, not rule-based. And the corpus used is not very big. 

If you know the words that are problematic beforehand, maybe you can create a replacement dictionary and preprocess the text before running EngTagger.
